# Generated by Django 3.1.7 on 2021-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='key',
            field=models.SlugField(blank=True, max_length=56, unique=True),
        ),
    ]
